version: 2.1

executors:
  ubuntu-focal:
    docker:
      - image: ubuntu:focal
  ubuntu-bionic:
    docker:
      - image: ubuntu:bionic

workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              os: [ubuntu-focal, ubuntu-bionic]
      - linter
jobs:
  build:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - run:
          name: System dependencies
          command: |
            set -ex
            PKG='apt-get install -y --no-install-recommends'
            export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
            echo "tzdata tzdata/Areas select Europe" > /tmp/preseed.txt
            echo "tzdata tzdata/Zones/Europe select Brussels" >> /tmp/preseed.txt
            debconf-set-selections /tmp/preseed.txt
            apt-get update -q
            $PKG tzdata 
            $PKG pkg-config cmake make build-essential m4 autotools-dev autoconf automake libtool
            $PKG yasm nasm
            $PKG libgtest-dev libgoogle-glog-dev libgoogle-glog0v5
      - run:
          name: Build isa-l_crypto
          command: |
            set -ex
            cd vendor/isa-l_crypto
            ./autogen.sh
            ./configure --prefix=/usr --enable-shared --enable-static
            make -j $(nproc --ignore=1)
            make install
      - run:
          name: Build and Test
          command: |
            cmake .
            make -j 4
            ./test-cpp-isal-crypto
            make test
  linter:
    docker:
      - image: ubuntu:focal
    steps:
      - checkout
      - run:
          name: System dependencies
          command: |
            PKG='apt-get install -y --no-install-recommends'
            set -ex
            export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
            echo "tzdata tzdata/Areas select Europe" > /tmp/preseed.txt
            echo "tzdata tzdata/Zones/Europe select Brussels" >> /tmp/preseed.txt
            debconf-set-selections /tmp/preseed.txt
            apt-get update -q
            $PKG tzdata
            $PKG pkg-config cmake make build-essential m4 autotools-dev autoconf automake libtool
            $PKG python virtualenv
            $PKG yasm nasm
            $PKG libgtest-dev libgoogle-glog-dev libgoogle-glog0v5
      - run:
          name: Python dependencies
          command: |
            virtualenv /tmp/env
            source /tmp/env/bin/activate
            pip install --upgrade cpplint
      - run:
          name: Build isa-l_crypto
          command: |
            set -ex
            cd vendor/isa-l_crypto
            ./autogen.sh
            ./configure --prefix=/usr --enable-shared --enable-static
            make -j $(nproc --ignore=1)
            make install
      - run:
          name: Build and Test
          command: |
            source /tmp/env/bin/activate
            cmake .
            make -j 4
            ./test-cpp-isal-crypto
            make test
