version: 2.1

executors:
  ubuntu-focal:
    docker:
      - image: ubuntu:focal
  ubuntu-bionic:
    docker:
      - image: ubuntu:bionic
  ubuntu-xenial:
    docker:
      - image: ubuntu:xenial

workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              os: [ubuntu-focal, ubuntu-bionic, ubuntu-xenial]
      - linter
jobs:
  build:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - run:
          name: System dependencies
          command: |
            apt-get update
            apt-get install -y git cmake make build-essential libgtest-dev
      - run:
          name: Fetch code dependencies
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Build and Test
          command: |
            cmake .
            make
            make test
  linter:
    docker:
      - image: ubuntu:focal
    steps:
      - checkout
      - run:
          name: System dependencies
          command: |
            apt-get update
            apt-get install -y virtualenv
            apt-get install -y git cmake make build-essential libgtest-dev
      - run:
          name: Fetch code dependencies
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Python dependencies
          command: |
            virtualenv /tmp/env
            source /tmp/env/bin/activate
            pip install --upgrade cpplint
      - run:
          name: Build and Test
          command: |
            cmake .
            make
            make test
